@aspnet_todolist_HostAddress = http://localhost:5276

###
GET {{aspnet_todolist_HostAddress}}

###
GET {{aspnet_todolist_HostAddress}}/todolist

###
POST {{aspnet_todolist_HostAddress}}/todolist
Content-Type: application/json
{
  "name":"task 1",
  "isComplete":false
}

###
POST {{aspnet_todolist_HostAddress}}/todolist
Content-Type: application/json
{
  "name":"task 2",
  "isComplete":false
}

###
PUT {{aspnet_todolist_HostAddress}}/todolist/1/complete